### ISSUE TITLE
Possible to have the same tool for Avax Node ?

### ISSUE THREAD

**Issue by TokreN** [zkoolkyle/BSC-Node-Block-Monitor#3]
Hi Kytixo,

Thank you for this cool tool ! Is it possible to have the same for Avax ?

Thanks !

**Comment by TokreN** [comment]
Secondly, i'm most of the time at 1 block ahead, do you have any advise / tips to improve the speed on bsc ? thanks !

**Comment by KyTiXo** [comment]
Hey @TokreN ty for the nice comments. I don't know enough about Avax but I think any blockchain that supports Geth Nodes should be compatible. I don't believe Avax nodes work this way after a quick a google search. 

As for your second question, that's basically why I built the tool. I was struggling to keep up with the BSC blockchain and kept falling behind using my server. After a ton of research, it appeared that many factors go into it but the main ones were HDD r/w speed + processor speed. You need tons of writing speed and decent internet basically.

Back in the day when I wrote this, people with i7's and SSDs were having trouble keeping up due to the blockchain block interval during heavy traffic times last year. While you may be in-sync now, heavy loads on the network can cause you to fall behind without top-tier gear. 

So my advice is find your bottleneck and upgrade it.
